export enum ROLES {
	DOCTOR = 'DOCTOR',
	ADMIN = 'ADMIN'
}

export const MONGODB_CONNECTION = 'MONGODB_CONNECTION'

export const USER_MODEL = 'USER_MODEL'

export const CONFIRMATION_TOKEN_MODEL = 'CONFIRMATION_TOKEN_MODEL'